services:
  workout:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workout
    restart: unless-stopped
    ports:
      - "8060:8060"
    volumes:
      - /srv/webdata/workout:/data
